trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  name: 1.1.$(BuildID)

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: '3.1.x'
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  displayName: 'Building and publishing'
  inputs:
    command: 'custom'
    projects: 'Ryujinx/Ryujinx.csproj'
    custom: 'msbuild'
    arguments: '-restore -t:PublishAllRids -p:Configuration="$(buildConfiguration)" -p:ArtifactStagingDirectory="$(Build.ArtifactStagingDirectory)" -p:Version="$(name)"'

- task: PublishBuildArtifacts@1
  displayName: "Upload Artifacts"
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'Ryujinx'